version: "3.9"

services:
  auth_db:
    image: postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/home/masud/www
    depends_on:
      - auth_db
